### ISSUE TITLE
Page 11

### ISSUE THREAD

**Issue by Bannerli** [xieliaing/Data_Science_Industrial_Practice#1]
极大似然估计函数  L(β) 中的Pit 中的 i 是指什么？

**Comment by xieliaing** [comment]
根据上下文，这是一个typo，应该是$\P_{jt}$，j表示第j个选项，t表示第t个决策者。已经纳入勘误，后续会修订。谢谢指出该问题。

**Comment by xieliaing** [comment]
closed #1
