### ISSUE TITLE
请教你几个书名。

### ISSUE THREAD

**Issue by hecaodong** [xieliaing/Data_Science_Industrial_Practice#2]
谢博士，你好。最近拜读了你、缪莹莹等所著的数据科学工程实践，感触良多。如你在前言中所说，这本书点明了关键节点，起到了引导作用。
所以我现在想沿着这个方向，再找一些资料进行学习。你能沿着这本书，给推荐几本书吗或者阅读材料，英文也可
”第三类是少部分互联网领域统计实 验的书，这类书多是外文，知识较新，阅读门槛较高，通常针对互联网 广告和搜索领域，在不理解理论背景的情况下也难以迁移到其他场景“
你在上面这段话中描述的书能推荐给我吗？
非常感谢你百忙中的回复。

**Comment by xieliaing** [comment]
感谢对本书的喜爱。互联网领域的实验书籍最受欢迎的是Ron Kohavi编写的《Trustworthy Online Controlled Experiments: A Practical Guide to A/B Testing》，国内翻译版为《关键迭代：可信赖的线上对照实验》，参见豆瓣书评：https://book.douban.com/subject/35434195/

另外，可以多看看统计领域的关于传统实验理论的书，这个领域书籍汗牛充栋，我个人使用的是John Lawson的《Design and Analysis of Experiments with R》（https://www.amazon.com/Analysis-Experiments-Chapman-Statistical-Science/dp/1439868131/ref=sr_1_8?keywords=design+and+analysis+of+experimentation&qid=1649726786&sr=8-8），
对于梳理不同场景下的适用设计及对应分析很有帮助。互联网实验都是其中传统案例的变形，无出其右，关键是要对照学习和应用。

**Comment by hecaodong** [comment]
感谢谢博士，百忙之中的回复，以及这本启发和实用兼具的书。
期待你们的下一本著作。
